name: Plugin 'Test' Command

on:
  workflow_dispatch:
    inputs:
      # These first two inputs are required in order for the slash command to function
      repository:
        description: 'The repository from which the slash command was dispatched'
        required: true
      comment-id:
        description: 'The comment-id of the slash command'
        required: true

jobs:
  draft_release:

    runs-on: ubuntu-latest
    permissions:
      contents: write       # to create a github release
      pull-requests: write  # to create and update PRs
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      PLUGIN_NAME: tap-github  # TODO: make dynamic from inputs

    steps:

    # # We actually don't need to checkout the repo (at least, not currently).
    # # Skipped deliberately:
    # - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v3.1.2
      with:
        # https://github.com/actions/setup-python
        python-version: 3.9
        # architecture: x64  # TODO: remove if not needed

    - name: Install plugin
      id: plugin-install
      run: |
        pipx install ${{ env.PLUGIN_NAME }} 2>&1 | tee install-output.txt

    - name: Print plugin help
      id: plugin-help
      run: |
        ${{ env.PLUGIN_NAME }} --help | tee help-output.txt

    - name: Print plugin version
      id: plugin-version
      continue-on-error: true
      run: |
        ${{ env.PLUGIN_NAME }} --version | tee help-output.txt

    - name: Print plugin about
      id: plugin-about
      continue-on-error: true
      run: |
        ${{ env.PLUGIN_NAME }} --about --format=json | tee about-result.json

    - name: Print plugin markdown
      id: plugin-markdown
      continue-on-error: true
      run: |
        ${{ env.PLUGIN_NAME }} --about --format=markdown | tee markdown-result.md

    - name: Add output as comment
      uses: peter-evans/create-or-update-comment@v2
      with:
        token: ${{ secrets.ACTIONS_BOT_TOKEN }}
        repository: ${{ github.event.inputs.repository }}
        body: |
          [The requested test operation is now running.](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}) :rocket:

    - name: Append 'starting' notification to comment
      uses: peter-evans/create-or-update-comment@v2
      with:
        comment-id: ${{ github.event.inputs.comment-id }}
        body: |
          > [Starting test job...](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}})

    - name: Add reaction (failure)
      uses: peter-evans/create-or-update-comment@v2
      if: ${{ failure() }}
      with:
        token: ${{ secrets.ACTIONS_BOT_TOKEN }}
        repository: ${{ github.event.inputs.repository }}
        comment-id: ${{ github.event.inputs.comment-id }}
        reaction-type: confused

    - name: Append comment (failure)
      if: ${{ failure() }}
      uses: peter-evans/create-or-update-comment@v2
      with:
        comment-id: ${{ github.event.inputs.comment-id }}
        body: |
          > Processing failed. :confused:

    - name: Add reaction (succcess)
      uses: peter-evans/create-or-update-comment@v2
      with:
        token: ${{ secrets.ACTIONS_BOT_TOKEN }}
        repository: ${{ github.event.inputs.repository }}
        comment-id: ${{ github.event.inputs.comment-id }}
        reaction-type: hooray

    - name: Append comment (success)
      if: steps.command-dispatch.outputs.error-message
      uses: peter-evans/create-or-update-comment@v2
      with:
        comment-id: ${{ github.event.inputs.comment-id }}
        body: |
          > Processing complete!
